version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/ioredis"
    versions:
    - 4.19.2
    - 4.19.3
    - 4.19.4
    - 4.22.0
    - 4.22.1
    - 4.22.2
    - 4.22.3
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.19
    - 5.12.0
    - 5.12.2
    - 5.12.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.3
  - dependency-name: gen-env-types
    versions:
    - 1.0.5
    - 1.2.0
  - dependency-name: helmet
    versions:
    - 4.4.1
